export const FETCH_STUDENTS= 'FETCH_STUDENTS';
export const STUDENTS_LOADING= 'STUDENTS_LOADING';
export const STUDENTS_FAILED = 'STUDENTS_FAILED';



export const FETCH_MENTORS= 'FETCH_MENTORS';
export const MENTORS_LOADING= 'MENTORS_LOADING';
export const MENTORS_FAILED = 'MENTORS_FAILED';


export const FETCH_COMPANIES= 'FETCH_COMPANIES';
export const COMPANIES_LOADING= 'COMPANIES_LOADING';
export const COMPANIES_FAILED = 'COMPANIES_FAILED';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';


